name: Build Artifact

on:
  push:
    branches: 'master'

env:
  SOLUTION_NAME: NoClippy

jobs:
  build:
    runs-on: [windows-2022]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SOLUTION_NAME }}.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: msbuild ${{ env.SOLUTION_NAME }}.sln /p:Configuration=Debug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: ./bin/Debug/*
